// const arr = [1,2,3,4,5]
// console.log(arr)
const arr2 = new Array(10,20,30,40)
// console.log(arr2)
// console.log(arr2[1])

// arr2.push(50)
// console.log(arr2)
// arr2.push(60)
// console.log(arr2)
// arr2.pop()
// console.log(arr2)
// arr2.unshift(0)
// console.log(arr2)
// arr2.shift()
// console.log(arr2)
// console.log(arr2.includes(100))
// console.log(arr2.indexOf(100))
// console.log(arr2.indexOf(10))

// const newarr = arr2.join()
// console.log(arr2)
// console.log(newarr)

console.log("a",arr2)
const mya1 = arr2.slice(1,3)
console.log(mya1)
console.log("b",arr2)
const mya2 = arr2.splice(1,3)
console.log(mya2)
console.log("c",arr2)

